# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
version: "3.4"
services:
  nautobot:
    command: "nautobot-server runserver 0.0.0.0:8080"
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"

  worker:
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"

  prometheus:
    image: "prom/prometheus:v2.33.1"
    command: "--storage.tsdb.retention.time=1d --config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    tty: true

  grafana:
    image: "grafana/grafana:8.3.6"
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "grafana_data:/var/lib/grafana"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ENABLE_GZIP: "true"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-googlesheets-datasource,grafana-worldmap-panel,natel-discrete-panel,grafana-github-datasource,agenty-flowcharting-panel,magnesium-wordcloud-panel,novatec-sdg-panel"
      GF_RENDERING_SERVER_URL: "http://renderer:8081/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
      GF_LOG_FILTERS: "rendering:debug"

  renderer:
    image: "grafana/grafana-image-renderer:3.4.0"
    ports:
      - "8081:8081"
    environment:
      ENABLE_METRICS: "true"

volumes:
  postgres_data: {}  # Nuatobot Postgres
  grafana_data: {}
  prometheus_data: {}
