{
 "title": "Network Automation Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Playbook",
    "query": "SELECT DISTINCT(playbook) FROM `jobs`"
   },
   {
    "name": "Site",
    "query": "SELECT DISTINCT(host) FROM job_hosts"
   },
   {
    "name": "Stage",
    "query": "SELECT DISTINCT(host) FROM job_hosts"
   },
   {
    "name": "Device",
    "query": "SELECT DISTINCT(host) FROM job_hosts"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs Run",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval),\n  count(distinct(jobs.id)) AS \"id\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1\nORDER BY $__timeGroup(jobs.started,$__interval)"
    }
   ]
  },
  {
   "title": "Chat Ops",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,0),\n  count(id) AS \"id\"\nFROM chat_jobs\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval,0)"
    }
   ]
  },
  {
   "title": "Manual Tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(log_time,$__interval),\n  count(id) AS \"id\"\nFROM tacacs_acct\nWHERE\n  $__timeFilter(log_time) AND device LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND device LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND device LIKE REPLACE(\"$Device%\", \"'\", \"%\")\nGROUP BY 1\nORDER BY $__timeGroup(log_time,$__interval)"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT now() as time_sec, jobs.status, count(distinct(jobs.id)) from jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Time Savings",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n    sum(playbook_cost.cost) / 60\nFROM\n    jobs\nLEFT JOIN playbook_cost ON \n    playbook_cost.playbook = jobs.playbook\nLEFT JOIN job_hosts ON \n    jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )"
    }
   ]
  },
  {
   "title": "Workflows by User",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "rawSql": "select user as User, count(distinct(id))as Chat FROM chat_jobs WHERE $__timeFilter(timestamp) group by user;"
    },
    {
     "rawSql": "SELECT jobs.created_by as User, count(distinct(jobs.id)) as Jobs FROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job WHERE $__timeFilter(started)AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) ) GROUP BY created_by;"
    },
    {
     "rawSql": "SELECT tacacs_acct.user as User, count(distinct(tacacs_acct.id)) as \"Manual\" FROM tacacs_acct WHERE $__timeFilter(tacacs_acct.log_time) AND tacacs_acct.device LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND tacacs_acct.device LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND tacacs_acct.device LIKE REPLACE(\"$Device%\", \"'\", \"%\") GROUP BY user;"
    }
   ]
  },
  {
   "title": "Cost Savings",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    sum(playbook_cost.cost) * 1.083333\nFROM\n    jobs\nLEFT JOIN playbook_cost ON \n    playbook_cost.playbook = jobs.playbook\nLEFT JOIN job_hosts ON \n    jobs.id = job_hosts.job    \nWHERE\n  $__timeFilter(jobs.started)AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )"
    }
   ]
  },
  {
   "title": "Total Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(job_hosts.host)) FROM `job_hosts`  LEFT JOIN jobs on job_hosts.job = jobs.id WHERE\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )"
    }
   ]
  },
  {
   "title": "% Automated",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select ((chat.chat + jobs.jobs) / (chat.chat + jobs.jobs + cli.cli) * 100) from\n  (select count(id) as chat from chat_jobs where $__timeFilter(timestamp) ) chat,\n  (select count(distinct(jobs.id)) as jobs FROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job WHERE\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook)) ) jobs,\n  (select count(tacacs_acct.id) as cli from tacacs_acct WHERE $__timeFilter(log_time) AND device LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND device LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND device LIKE REPLACE(\"$Device%\", \"'\", \"%\")) cli;"
    }
   ]
  },
  {
   "title": "Avg Job Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(UNIX_TIMESTAMP(jobs.finished) - UNIX_TIMESTAMP(jobs.started)) as metric\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(jobs.started)AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )"
    }
   ]
  },
  {
   "title": "Top Hosts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT job_hosts.host, count(job_hosts.host) as metric FROM `job_hosts` LEFT JOIN jobs on job_hosts.job = jobs.id WHERE\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) ) GROUP BY job_hosts.host order by metric desc"
    }
   ]
  },
  {
   "title": "Top Failed Hosts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT job_hosts.host, count(job_hosts.host) as metric FROM `job_hosts` LEFT JOIN jobs on job_hosts.job = jobs.id WHERE (job_hosts.failures > 0 or job_hosts.unreachable > 0) AND\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) ) GROUP BY job_hosts.host order by metric desc"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Successful Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval,0),\n  jobs.playbook AS metric,\n  count(distinct(jobs.id)) AS \"id\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND\n  status = 'successful' AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1,2\nORDER BY $__timeGroup(started,$__interval,0)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval,0),\n  jobs.playbook AS metric,\n  count(distinct(jobs.id)) AS \"id\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND\n  status = 'failed' AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1,2\nORDER BY $__timeGroup(started,$__interval,0)"
    }
   ]
  },
  {
   "title": "Successful Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval,0),\n  jobs.playbook AS metric,\n  count(distinct(jobs.id)) AS \"id\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND\n  status = 'successful' AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1,2\nORDER BY $__timeGroup(started,$__interval,0)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval,0),\n  jobs.playbook AS metric,\n  count(distinct(jobs.id)) AS \"id\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND\n  status = 'failed' AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1,2\nORDER BY $__timeGroup(started,$__interval,0)"
    }
   ]
  },
  {
   "title": "Job Success/Fail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval,0),\n  jobs.status AS metric,\n  count(distinct(jobs.id)) AS \"id\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1,2\nORDER BY $__timeGroup(started,$__interval,0)"
    }
   ]
  },
  {
   "title": "Playbook Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(started,$__interval,0), jobs.playbook, (UNIX_TIMESTAMP(jobs.finished) - UNIX_TIMESTAMP(jobs.started)) as Execution from jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job WHERE \n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) ) ORDER BY $__timeGroup(started,$__interval,previous)"
    }
   ]
  },
  {
   "title": "Host Stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT job_hosts.host, sum(job_hosts.changed)as changed, sum(job_hosts.failures) as failures, sum(job_hosts.ok) as ok, sum(job_hosts.unreachable) as unreachable, sum(job_hosts.skipped) as skipped FROM `job_hosts`  LEFT JOIN jobs on job_hosts.job = jobs.id WHERE\n  $__timeFilter(jobs.started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )   GROUP BY job_hosts.host"
    }
   ]
  },
  {
   "title": "Avg Time by Job",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  jobs.playbook as Playbook, AVG(UNIX_TIMESTAMP(jobs.finished) - UNIX_TIMESTAMP(jobs.started)) as Execution\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(jobs.started)AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\ngroup by playbook"
    }
   ]
  },
  {
   "title": "Job Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(jobs.started,$__interval,0),\n  jobs.playbook AS metric,\n  count(jobs.playbook) AS \"playbook\"\nFROM jobs LEFT JOIN job_hosts on jobs.id = job_hosts.job\nWHERE\n  $__timeFilter(started) AND host LIKE REPLACE(\"$Site%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Stage%\", \"'\", \"%\") AND host LIKE REPLACE(\"$Device%\", \"'\", \"%\") AND (jobs.playbook like TRIM(BOTH '\"' FROM \"$Playbook\") OR jobs.playbook IN ($Playbook) )\nGROUP BY 1, playbook,2\nORDER BY $__timeGroup(started,$__interval,0)"
    }
   ]
  },
  { "title": "Chat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Chat Commands",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  command AS metric,\n  count(id) AS \"id\"\nFROM chat_jobs\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Chat Commands (Total)",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  command, count(distinct(id)) as total\nFROM chat_jobs\nWHERE\n  $__timeFilter(timestamp)\ngroup by command;"
    }
   ]
  },
  {
   "title": "Chat Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,0),\n  command AS metric,\n  count(command) AS \"command\"\nFROM chat_jobs\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1, command ,2\nORDER BY $__timeGroup(timestamp,$__interval,0)"
    }
   ]
  }
 ]
}