# Generated by Django 3.1.3 on 2021-02-22 02:18

import django.contrib.postgres.fields
from django.db import migrations, models
from django.core.serializers.json import DjangoJSONEncoder
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("dashboard_slug", models.CharField(max_length=255)),
                ("dashboard_uid", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["dashboard_slug"],
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("command_name", models.CharField(max_length=64)),
                ("panel_id", models.IntegerField()),
                ("friendly_name", models.CharField(max_length=64)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nautobot_plugin_chatops_grafana.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["command_name"],
            },
        ),
        migrations.CreateModel(
            name="PanelVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("friendly_name", models.CharField(max_length=64)),
                ("query", models.CharField(max_length=64)),
                ("includeincmd", models.BooleanField(default=False)),
                ("includeinurl", models.BooleanField(default=True)),
                ("modelattr", models.CharField(max_length=32)),
                ("value", models.CharField(max_length=64)),
                ("response", models.CharField(max_length=255)),
                (
                    "filter",
                    models.JSONField(blank=True, default=dict, encoder=DjangoJSONEncoder),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nautobot_plugin_chatops_grafana.panel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
